function varargout = DetailInfo(varargin)

Detail_mssg={'The purpose of this program is to teach a computer to classify plants via their leaves.';' ';'We utilize the PNN (Probabilistic Neural Network) to implement this AI process. 12 characters of leaves are taken into account, including geometrical ones and morphological ones. After discriminant analysis (stepwise method), all these characters are reserved. PCA orthogonalizes these 12 characters into 5 principal variables, which consist input vectors of the PNN.';' '; 'Presently, our system can classify 32 common plants in Yangtze Delta(Shanghai is just there), China , such as Phyllestachys pubescens, Aesculus chinensis, Berberis , Cercis chinensis, Indigofera tinetoria, Acer Dalmatum, Phoebe zhennan, Kalopanax septemlobus, Cinnamomum japonicum, Koelreuteria paniculata, Ilex macrocarpa, Pittosporum tobira, I am sorry(error), Chimonanthus praecox, Cinnamomum camphora, Viburnum awabuki, Osmanthus fragrans, Cedrus deodara, Ginkgo biloba, Lagerstroemia indica, Nerium indcus, Podocarpus macrophyllus, Prunus yedoensis, Ligustrum quihoui, Toona sinensis, Amygdalus persica, Manglietia fordiana, Acer buergerianum, Mahonia bealei, Populus canadensis Moench, Liriodendron chinense, Citrus reticulata. '; ' ';'The average accuracy is 93% for all of them.'};

hd=figure('MenuBar','none','Position',[300.3333  100.0000  614.4000  256.000+70], 'Name', 'Detailed Information about our algorithm');

hDsp = uicontrol(hd,'Style','text',...
		'String',Detail_mssg,...
		'HorizontalAlignment','left',...
		'BackgroundColor','white',...
		'FontSize',13,...
              'Position',[5  30 607 290]);

CloseB = uicontrol('Style', 'pushbutton', 'String', 'OK',...
    'Position', [570 5 40 20], 'Callback', 'close');
